# ----- DATA CONFIGURATION -----
# Use state abbreviations for the sections.
[NC]
DB_NAME = # Name of database
CMU_SHP = # CMU centroid point shapefile name
CMU_SHP_COL_CMU_NAME = # CMU name column name in "CMU_SHP"
CMU_SHP_COL_RAIN_IN = # CMU rain threshold in inches column name in "CMU_SHP"
LEASE_SHP = # Leases centroid point shapefile name
LEASE_SHP_COL_LEASE_ID = # Lease ID column name in "LEASE_SHP"
LEASE_SHP_COL_CMU_NAME = # CMU column name in "LEASE_SHP"
LEASE_SHP_COL_RAIN_IN = # Rain threshold in inches column name in "LEASE_SHP"
LON_WE = # See https://www.cpc.ncep.noaa.gov/products/wesley/wgrib2/small_grib.html (e.g. -79:-75)
LAT_SN = # See https://www.cpc.ncep.noaa.gov/products/wesley/wgrib2/small_grib.html (e.g. 33:37)

[SC]
DB_NAME = # Name of database
LEASE_SHP = # Leases boundary shapefile name
LEASE_SHP_COL_LEASE_ID = # Lease ID column name in "LEASE_SHP"
LEASE_SHP_COL_CMU_NAME = # CMU column name in "LEASE_SHP"
THRESHOLD = # Rain threshold (e.g. 4)
LON_WE = # See https://www.cpc.ncep.noaa.gov/products/wesley/wgrib2/small_grib.html (e.g. -81:-78)
LAT_SN = # See https://www.cpc.ncep.noaa.gov/products/wesley/wgrib2/small_grib.html (e.g. 32:34)

# ----- DATABASE CONNECTIONS -----
# Use gpc.mysql for release version.
[gcp.mysql]
DB_USER = # DB username
DB_PASS = # DB Password
HOST = # Host address
PORT = # Port number

[gcp.bucket]
BUCKET_NAME = # Bucket name

[Notification]
ENCRYPTION_KEY_ENV = # Environment variable name for encryption key
GMAIL_API_CREDENTIAL_FILE = # Gmail API credential file path
GMAIL_API_TOKEN_FILE = # Gmail API token file path
EMAIL_SENDER = # Sender email address
DB_STORED_PROCEDURE = # Stored procedure name
EMAIL_SENDER = # Sender email address

[FL.Developer]
EMAIL_RECEIVER = # Email receiver: separate by comma for multiple receivers (e.g. address1, address2)   
SEND_EMAIL_TO_DEVELOPER = true # Use lowercase true or false for boolean values

[FL.Notification]
ENABLE_NOTIFICATIONS = true # Use lowercase true or false for boolean values

[NC.Notification]
ENABLE_NOTIFICATIONS = true # Use lowercase true or false for boolean values

[SC.Notification]
ENABLE_NOTIFICATIONS = true # Use lowercase true or false for boolean values

# ----- SAVE TO DATABASE -----
# This is helpful for developers to save or not save probability data to the database.
[FL.SaveToDB]
SAVE_TO_DB = true # Use lowercase true or false for boolean values

[NC.SaveToDB]
SAVE_TO_DB = true # Use lowercase true or false for boolean values

[SC.SaveToDB]
SAVE_TO_DB = true # Use lowercase true or false for boolean values
